### Obtener listado
GET http://localhost:3000/api/platos

### Obtener plato por ID
GET http://localhost:3000/api/platos/2


### Crear nuevo plato
POST http://localhost:3000/api/platos
Content-Type: application/json

{
    "nombre": "Tira de Asado",
    "precio": 12.50,
    "ingredientes": [
        "Carne de res",
        "Sal",
        "Pimienta"
    ],
    "tipoPlato": {
        "idTipoPlato": "2",
        "nombre": "Plato Principal"
    },
    "imagen": "https://example.com/ensalada-cesar.jpg"
}

### Modificar plato (PUT Y PATCH)
PUT http://localhost:3000/api/platos/3
Content-Type: application/json

{
    "nombre": "Prueba PUT",
    "precio": 1560,
    "ingredientes": [
        "Carne de res",
        "Sal",
        "Pimienta"
    ],
    "tipoPlato": {
        "idTipoPlato": "2",
        "nombre": "Plato Principal"
    },
    "imagen": "https://example.com/ensalada-cesar.jpg"
}

### Modificar plato (PATCH)
PATCH http://localhost:3000/api/platos/3
Content-Type: application/json

{
    "nombre": "Prueba PATCH",
    "precio": 1560,
    "ingredientes": [
        "patch prueba",
        "Sal",
        "Pimienta"
    ]
}

### Eliminar plato - DELETE
DELETE http://localhost:3000/api/platos/3